service: countriesApi
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
  memorySize: 256
functions:
  app:
    handler: server/dist/lambda.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true